# Generated by Django 3.1.2 on 2021-01-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_personal_info_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_personal_info',
            name='original_bag',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
