# Generated by Django 3.1.2 on 2020-11-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=254)),
                ('team_1_name', models.CharField(max_length=254)),
                ('team_2_name', models.CharField(max_length=254)),
                ('team_3_name', models.CharField(max_length=254)),
                ('team_1_time', models.IntegerField()),
                ('team_2_time', models.IntegerField()),
                ('team_3_time', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Leaderboards',
            },
        ),
    ]
