# Generated by Django 3.1.2 on 2020-11-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboards',
            name='team_1_time',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='leaderboards',
            name='team_2_time',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='leaderboards',
            name='team_3_time',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
