# Generated by Django 3.1.2 on 2021-01-18 15:07

import bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_room_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_booking',
            name='date',
            field=models.DateField(validators=[bookings.models.min_date]),
        ),
    ]
