# Generated by Django 3.1.2 on 2021-01-26 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_personal_info_user_profile'),
        ('bookings', '0004_auto_20210118_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_booking',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='checkout.order_personal_info'),
        ),
    ]
